//! Auto-generated comparison tests for C vs Rust behavioral equivalence.
//! Generated by scripts/generate-comparison-tests.py
//! 
//! DO NOT EDIT — regenerate with: python3 scripts/generate-comparison-tests.py

use expat_rust::xmlparse::Parser;
use expat_sys::CParser;

fn parse_rust(xml: &[u8]) -> (u32, u32) {
    let mut parser = Parser::new(None).unwrap();
    let status = parser.parse(xml, true);
    let error = parser.error_code();
    (status as u32, error as u32)
}

fn parse_c(xml: &[u8]) -> (u32, u32) {
    let parser = CParser::new(None).unwrap();
    let (status, error) = parser.parse(xml, true);
    (status, error)
}

fn compare(xml: &[u8], desc: &str) {
    let (rs, re) = parse_rust(xml);
    let (cs, ce) = parse_c(xml);
    assert!(rs == cs && re == ce,
        "MISMATCH {desc}: Rust status={rs} err={re}, C status={cs} err={ce}, input={:?}",
        std::str::from_utf8(xml).unwrap_or("<binary>"));
}

/// Compare incremental parsing: split input at every byte position
fn compare_incremental(xml: &[u8], desc: &str) {
    // First compare single-call
    compare(xml, desc);
    // Then compare split at each byte boundary
    for split in 1..xml.len() {
        let mut r_parser = Parser::new(None).unwrap();
        let r1 = r_parser.parse(&xml[..split], false);
        let r_final = if r1 == expat_rust::xmlparse::XmlStatus::Ok {
            r_parser.parse(&xml[split..], true)
        } else {
            r1
        };
        let r_err = r_parser.error_code();

        let c_parser = CParser::new(None).unwrap();
        let (c1, _) = c_parser.parse(&xml[..split], false);
        let (c_final, c_err) = if c1 == 1 { // XML_STATUS_OK
            c_parser.parse(&xml[split..], true)
        } else {
            (c1, c_parser.parse(&xml[split..], true).1)
        };

        let rs = r_final as u32;
        let re = r_err as u32;
        assert!(rs == c_final && re == c_err,
            "INCREMENTAL MISMATCH {desc} split@{split}: Rust status={rs} err={re}, C status={c_final} err={c_err}");
    }
}

fn compare_ns(xml: &[u8], desc: &str) {
    // NS tests use non-NS parser for now — still catches basic parse errors
    compare(xml, desc);
}

#[test]
fn gen_empty_root() {
    compare(b"<r/>", "minimal self-closing element");
}

#[test]
fn gen_root_with_text() {
    compare(b"<r>text</r>", "text content");
}

#[test]
fn gen_root_with_whitespace() {
    compare(b"<r> \t\n </r>", "whitespace content");
}

#[test]
fn gen_nested_3_deep() {
    compare(b"<a><b><c/></b></a>", "3 levels deep");
}

#[test]
fn gen_multiple_children() {
    compare(b"<r><a/><b/><c/></r>", "multiple children");
}

#[test]
fn gen_attrs_single_quotes() {
    compare(b"<r a='1'/>", "single-quoted attributes");
}

#[test]
fn gen_attrs_double_quotes() {
    compare(b"<r a=\"1\"/>", "double-quoted attributes");
}

#[test]
fn gen_multiple_attrs() {
    compare(b"<r a=\"1\" b=\"2\" c=\"3\"/>", "multiple attributes");
}

#[test]
fn gen_attr_with_entities() {
    compare(b"<r a=\"&amp;&lt;&gt;\"/>", "entities in attributes");
}

#[test]
fn gen_empty_attr() {
    compare(b"<r a=\"\"/>", "empty attribute value");
}

#[test]
fn gen_xmldecl_10() {
    compare(b"<?xml version='1.0'?><r/>", "xml decl version 1.0");
}

#[test]
fn gen_xmldecl_utf8() {
    compare(b"<?xml version='1.0' encoding='utf-8'?><r/>", "xml decl with encoding");
}

#[test]
fn gen_xmldecl_standalone_yes() {
    compare(b"<?xml version='1.0' standalone='yes'?><r/>", "standalone yes");
}

#[test]
fn gen_xmldecl_standalone_no() {
    compare(b"<?xml version='1.0' standalone='no'?><r/>", "standalone no");
}

#[test]
fn gen_xmldecl_all() {
    compare(b"<?xml version='1.0' encoding='utf-8' standalone='yes'?><r/>", "all xml decl attrs");
}

#[test]
fn gen_comment_before() {
    compare(b"<!-- comment --><r/>", "comment before root");
}

#[test]
fn gen_comment_after() {
    compare(b"<r/><!-- comment -->", "comment after root");
}

#[test]
fn gen_comment_inside() {
    compare(b"<r><!-- inside --></r>", "comment inside element");
}

#[test]
fn gen_comment_empty() {
    compare(b"<r><!----></r>", "empty comment");
}

#[test]
fn gen_comment_with_dashes() {
    compare(b"<r><!-- a-b --></r>", "comment with dashes");
}

#[test]
fn gen_pi_before() {
    compare(b"<?target data?><r/>", "PI before root");
}

#[test]
fn gen_pi_after() {
    compare(b"<r/><?target data?>", "PI after root");
}

#[test]
fn gen_pi_inside() {
    compare(b"<r><?target data?></r>", "PI inside element");
}

#[test]
fn gen_pi_no_data() {
    compare(b"<r><?target?></r>", "PI without data");
}

#[test]
fn gen_cdata_simple() {
    compare(b"<r><![CDATA[hello]]></r>", "simple CDATA");
}

#[test]
fn gen_cdata_with_lt() {
    compare(b"<r><![CDATA[<not-a-tag>]]></r>", "CDATA with <");
}

#[test]
fn gen_cdata_with_amp() {
    compare(b"<r><![CDATA[a&b]]></r>", "CDATA with &");
}

#[test]
fn gen_cdata_empty() {
    compare(b"<r><![CDATA[]]></r>", "empty CDATA");
}

#[test]
fn gen_cdata_with_brackets() {
    compare(b"<r><![CDATA[a]b]]></r>", "CDATA with ]");
}

#[test]
fn gen_entity_amp() {
    compare(b"<r>&amp;</r>", "amp entity");
}

#[test]
fn gen_entity_lt() {
    compare(b"<r>&lt;</r>", "lt entity");
}

#[test]
fn gen_entity_gt() {
    compare(b"<r>&gt;</r>", "gt entity");
}

#[test]
fn gen_entity_quot() {
    compare(b"<r>&quot;</r>", "quot entity");
}

#[test]
fn gen_entity_apos() {
    compare(b"<r>&apos;</r>", "apos entity");
}

#[test]
fn gen_charref_decimal() {
    compare(b"<r>&#65;</r>", "decimal char ref A");
}

#[test]
fn gen_charref_hex() {
    compare(b"<r>&#x41;</r>", "hex char ref A");
}

#[test]
fn gen_charref_multibyte() {
    compare(b"<r>&#x00e9;</r>", "char ref for é");
}

#[test]
fn gen_multiple_entities() {
    compare(b"<r>&amp;&lt;&gt;</r>", "multiple entities");
}

#[test]
fn gen_doctype_simple() {
    compare(b"<!DOCTYPE r><r/>", "simple DOCTYPE");
}

#[test]
fn gen_doctype_system() {
    compare(b"<!DOCTYPE r SYSTEM \"test.dtd\"><r/>", "DOCTYPE with SYSTEM");
}

#[test]
fn gen_doctype_public() {
    compare(b"<!DOCTYPE r PUBLIC \"-//Test\" \"test.dtd\"><r/>", "DOCTYPE with PUBLIC");
}

#[test]
fn gen_doctype_internal_empty() {
    compare(b"<!DOCTYPE r []><r/>", "DOCTYPE with empty internal subset");
}

#[test]
fn gen_doctype_entity_decl() {
    compare(b"<!DOCTYPE r [<!ENTITY e \"val\">]><r/>", "DOCTYPE with entity");
}

#[test]
fn gen_doctype_attlist() {
    compare(b"<!DOCTYPE r [<!ATTLIST r a CDATA #IMPLIED>]><r/>", "DOCTYPE with ATTLIST");
}

#[test]
fn gen_doctype_element_any() {
    compare(b"<!DOCTYPE r [<!ELEMENT r ANY>]><r/>", "DOCTYPE with ELEMENT ANY");
}

#[test]
fn gen_doctype_element_empty() {
    compare(b"<!DOCTYPE r [<!ELEMENT r EMPTY>]><r/>", "DOCTYPE with ELEMENT EMPTY");
}

#[test]
fn gen_doctype_notation() {
    compare(b"<!DOCTYPE r [<!NOTATION n SYSTEM \"test\">]><r/>", "DOCTYPE with NOTATION");
}

#[test]
fn gen_doctype_comment() {
    compare(b"<!DOCTYPE r [<!-- comment -->]><r/>", "DOCTYPE with comment");
}

#[test]
fn gen_doctype_pi() {
    compare(b"<!DOCTYPE r [<?pi data?>]><r/>", "DOCTYPE with PI");
}

#[test]
fn ext_err_empty_final() {
    compare(b"", "empty input with is_final");
}

#[test]
fn ext_err_no_root() {
    compare(b"   ", "whitespace only");
}

#[test]
fn ext_err_unclosed_tag() {
    compare(b"<r>", "unclosed tag");
}

#[test]
fn ext_err_mismatched_tags() {
    compare(b"<a></b>", "mismatched tags");
}

#[test]
fn ext_err_double_root() {
    compare(b"<r/><r/>", "two root elements");
}

#[test]
fn ext_err_text_after_root() {
    compare(b"<r/>text", "text after root");
}

#[test]
fn ext_err_invalid_char() {
    compare(b"<r>\x00</r>", "null byte in content");
}

#[test]
fn ext_err_bad_entity() {
    compare(b"<r>&nosuch;</r>", "undefined entity");
}

#[test]
fn ext_err_bad_charref() {
    compare(b"<r>&#xFFFFFF;</r>", "invalid char ref");
}

#[test]
fn ext_err_unclosed_entity() {
    compare(b"<r>&amp</r>", "unclosed entity ref");
}

#[test]
fn ext_err_duplicate_attr() {
    compare(b"<r a=\"1\" a=\"2\"/>", "duplicate attribute");
}

#[test]
fn ext_err_junk_in_prolog() {
    compare(b"xxx<r/>", "junk before root");
}

#[test]
fn ext_err_misplaced_xmldecl() {
    compare(b"<r/><?xml version='1.0'?>", "xml decl after root");
}

#[test]
fn ext_err_trailing_cr() {
    compare(b"<r>\r", "trailing CR in content");
}

#[test]
fn ext_err_partial_tag() {
    compare(b"<r", "partial opening tag");
}

#[test]
fn gen_ws_before_root() {
    compare(b"  \n  <r/>", "whitespace before root");
}

#[test]
fn gen_ws_after_root() {
    compare(b"<r/>  \n  ", "whitespace after root");
}

#[test]
fn gen_ws_crlf() {
    compare(b"<r>a\r\nb</r>", "CRLF in content");
}

#[test]
fn gen_ws_cr_only() {
    compare(b"<r>a\rb</r>", "bare CR in content");
}

#[test]
fn gen_ws_in_attr() {
    compare(b"<r a = \"1\" />", "whitespace around = in attrs");
}

#[test]
fn gen_ns_default() {
    compare_ns(b"<r xmlns=\"http://example.com\"/>", "default namespace");
}

#[test]
fn gen_ns_prefix() {
    compare_ns(b"<x:r xmlns:x=\"http://example.com\"/>", "prefixed namespace");
}

#[test]
fn gen_ns_nested_override() {
    compare_ns(b"<r xmlns=\"http://a\"><c xmlns=\"http://b\"/></r>", "nested namespace override");
}

#[test]
fn gen_ns_unbound_prefix_err() {
    compare_ns(b"<x:r/>", "unbound prefix error");
}

#[test]
fn gen_ns_on_attribute() {
    compare_ns(b"<r xmlns:x=\"http://example.com\" x:a=\"1\"/>", "namespace on attribute");
}

#[test]
fn gen_utf8_2byte() {
    compare(b"<r>\xc3\xa9</r>", "2-byte UTF-8 (é)");
}

#[test]
fn gen_utf8_3byte() {
    compare(b"<r>\xe4\xb8\xad</r>", "3-byte UTF-8 (中)");
}

#[test]
fn gen_utf8_4byte() {
    compare(b"<r>\xf0\x9f\x98\x80</r>", "4-byte UTF-8 (😀)");
}

#[test]
fn gen_utf8_in_attr() {
    compare(b"<r a=\"\xc3\xa9\"/>", "UTF-8 in attribute");
}

#[test]
fn gen_utf8_in_name() {
    compare(b"<r\xc3\xa9/>", "UTF-8 in element name");
}


// ======================== Incremental parsing tests ========================
// These split inputs at every byte boundary to test buffering logic

#[test]
fn incr_simple() { compare_incremental(b"<r/>", "incremental simple"); }

#[test]
fn incr_with_content() { compare_incremental(b"<r>hello</r>", "incremental with content"); }

#[test]
fn incr_with_attrs() { compare_incremental(b"<r a='1' b='2'/>", "incremental with attrs"); }

#[test]
fn incr_xmldecl() { compare_incremental(b"<?xml version='1.0'?><r/>", "incremental xmldecl"); }

#[test]
fn incr_doctype() { compare_incremental(b"<!DOCTYPE r><r/>", "incremental doctype"); }

#[test]
fn incr_cdata() { compare_incremental(b"<r><![CDATA[data]]></r>", "incremental cdata"); }

#[test]
fn incr_comment() { compare_incremental(b"<r><!-- comment --></r>", "incremental comment"); }

#[test]
fn incr_pi() { compare_incremental(b"<r><?target data?></r>", "incremental pi"); }

#[test]
fn incr_charref() { compare_incremental(b"<r>&#65;&#x42;</r>", "incremental charref"); }

#[test]
fn incr_entity() { compare_incremental(b"<r>&amp;&lt;&gt;</r>", "incremental entities"); }

#[test]
fn incr_nested() { compare_incremental(b"<a><b><c/></b></a>", "incremental nested"); }

#[test]
fn incr_epilog() { compare_incremental(b"<r/>\n<!-- done -->\n", "incremental epilog"); }

#[test]
fn incr_utf8() { compare_incremental(b"<r>\xc3\xa9</r>", "incremental utf8"); }

#[test]
fn incr_dtd_entity() { compare_incremental(b"<!DOCTYPE r [<!ENTITY e 'val'>]><r>&e;</r>", "incremental dtd entity"); }

#[test]
fn incr_empty_element() { compare_incremental(b"<r><a/><b/></r>", "incremental empty elements"); }
